### ISSUE TITLE
No authentication listener registered for firewall "oauth_token"

### ISSUE THREAD

**Issue by mappedinn** [bitgandtter/k8s_php_test#2]
Hi YASMANY CUBELA MEDINA @bitgandtter 

Thanks for [the tutorial](https://bitgandtter.wordpress.com/2015/09/10/symfony-a-restful-app-security-securing-the-token-path/) you are providing... It really helped me to get FOSOAuthServerBundle working.

The configuration you are providing for securing oauth_token seems to be incomplete. In fact, I am getting the following error **No authentication listener registered for firewall "oauth_token"** when trying to get an access token for the client.

May be you should specify a way on how to login since the security is activated.

        oauth_token:
            pattern:      ^/oauth/v2/token
            security:     true
            # form_login could be a solution here.

One more thing, You said it is not good send the password in plain text in the request for getting an access token, but the password is still there!!! Is it supposed to be sent in the header **only**??? 

    /oauth/v2/token?client_id=86_5sq[...]&client_secret=3er1d[...]&grant_type=password&redirect_uri=www.example.com&username=fabien&password=fabien

One last thing, how to generate the hash for the password? A link on that would be great.

**Comment by bitgandtter** [comment]
Hello, a pleasure to help.

Regarding the listener, please review the configuration, the important value to notice is the type "rest: true" on firewall that refers to the:

`public function getKey() { return 'rest'; }`

function of the RestFactory class.

The steps to login are in fact explained after that condiguration, sending the request to the /oauth/v2/token endpoint with the new headers.

About the plain password on request you should read the [next post](https://bitgandtter.wordpress.com/2015/09/30/symfony-a-restful-app-security-securing-the-token-path-fixed/)

About the last question, the password can be hash with any algorithm of your choose i advice to use bcrypt but that is really up to the business requirements.

Cheers

**Comment by mappedinn** [comment]
Thank you very much for quick answer.

The new configuration as you noticed me is as follows:

    security:
      encoders:
          FOS\UserBundle\Model\UserInterface: bcrypt

      role_hierarchy:
          ROLE_USER : ROLE_API
          ROLE_ADMIN: ROLE_USER
          ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

      providers:
          # in_memory:
          #     memory:
          #         users:
          #             restapi:  { password: secretpw, roles: [ 'ROLE_API' ] }
          fos_userbundle:
              id: fos_user.user_provider.username

      firewalls:
          dev:
              pattern:      ^/(_(profiler|wdt)|css|images|js)/
              security:     false

          # the config of the firewall oauth_token as you recommended me
          oauth_token:
              pattern:      ^/oauth/v2/token
              rest:         true
              # security:     false

          api_doc:
              pattern:      ^/api/doc
              security:     false

          api:
             pattern: ^/api
             fos_oauth: true
             stateless: true
      access_control:
          - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] } #  IS_AUTHENTICATED_ANONYMOUSLY

Now, I am getting a new error: **Unrecognized option "rest" under "security.firewalls.oauth_token"**

Do you thing I missed something from the config?

Thanks again

**Comment by mappedinn** [comment]
@bitgandtter  I already implemented the service `oauth.storage` as it described in the next post and I do still have the same error: **Unrecognized option "rest" under "security.firewalls.oauth_token"**.

Do you have any idea?

Thanks in advance again...

**Comment by bitgandtter** [comment]
Seems to be something with the service configuration, please review that you have it enable it on your services.yml

**Comment by mappedinn** [comment]
Below are there services according the tutorial in its 3 parts:

    rest.security.authentication.provider:
        class: Minn\OAuthServerBundle\Security\Authentication\Provider\RestProvider
        arguments: [""]
        public: false

    rest.security.authentication.listener:
        class: Minn\OAuthServerBundle\Security\Firewall\RestListener
        arguments: ["@security.token_storage", "@security.authentication.manager"]
        public: false

    oauth.storage:
        class: Minn\OAuthServerBundle\Services\OAuthStorage
        arguments:
            - "@fos_oauth_server.client_manager"
            - "@fos_oauth_server.access_token_manager"
            - "@fos_oauth_server.refresh_token_manager"
            - "@fos_oauth_server.auth_code_manager"
            - "@fos_oauth_server.user_provider"
            - "@security.encoder_factory"
        public: false


Since all the services are not public, so a quick check by command console returned none of these services.

**Once I changed them to public**, I can find the `oauth.storage` by this command:

    $ php app/console debug:container | grep oauth.storage
    fos_oauth_server.storage   alias for "oauth.storage"                                                                   
    oauth.storage                    Minn\OAuthServerBundle\Services\OAuthStorage 


Any comment?

**Comment by mappedinn** [comment]
I found one mistake. I was using a non correct grant type! It was `client_credentials`.

I corrected the grant type and then I requested an access token with the config `rest:true`. The error is still the same.

I removed the config `rest:true` and the result become: 
    
    {"error":"invalid_grant","error_description":"Invalid username and password combination"}


This result is normal since the documentation requested that the password is passed through header with hash (**I guess here CURL command should be used for setting the header**).

I deleted all the declarations of the services proposed in the documentation, just to check if the request for the access token is correct. This was successful:

    {"access_token":"ZjA4MzExMjY0OTBiZjcwOGE4MTlkZmFhYjlhMmQwMjViY2IwYjZiMWZiZDc3MWNlMzQxMzA1YWU3MDQxNGZjNg","expires_in":3600,"token_type":"bearer","scope":"api","refresh_token":"OWJmYmVlY2E4NDhiYmU4MjY1YTcxNWE4NzkwY2RlMzAyNjM1MWVlMWQ0NjY2OWQ1MzkwMTE3MWYyNjhkZGMzNg"}


Can you tell me the idea behind setting the firewall with `rest: true`???

Thanks again & sorry for bothering you by my questions (I still fresh with OAuth2)

**Comment by bitgandtter** [comment]
On the definition for the REST Authentication Listener we define a new key `rest` that key is the one you use under a firewall you wanna authentication with that listener

**Comment by mappedinn** [comment]
thank you very much for being helpul
